<a href="https://colab.research.google.com/github/z-zaremska/PK_ML_Bootcamp/blob/master/supervised/02_regression/01_linear_regression_normal_equation_zz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

# Linear Regression (Numpy)

In [4]:
x1 = np.array([1, 2, 3, 4, 5, 6])
y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(x1)

In [5]:
x1

array([1, 2, 3, 4, 5, 6])

In [15]:
x1 = x1.reshape(m, 1)
print(x1)
print(f"x1.shape: {x1.shape}")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
x1.shape: (6, 1)


In [19]:
# Wektor wyrazów wolnych
bias = np.ones((m, 1))
print(bias)
print(f"bias.shape: {bias.shape}")

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
bias.shape: (6, 1)


In [21]:
#
x = np.append(bias, x1, axis=1)
print(x)
print(f"x.shape: {x.shape}")

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
x.shape: (6, 2)


In [32]:
x.T

array([[1., 1., 1., 1., 1., 1.],
       [1., 2., 3., 4., 5., 6.]])

In [30]:
# Mnożenie macierzy: x.T * x
np.dot(x.T, x)

array([[ 6., 21.],
       [21., 91.]])

In [35]:
# Macież do potęgi -1
l = np.linalg.inv(np.dot(x.T, x))
l

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [38]:
w = np.dot(l, np.dot(x.T, y))
w

array([2750.,  250.])

In [45]:
w0, w1 = w

def calc_linear_regression(a, b, x):
  return a*x + b

calc_linear_regression(w1, w0, 7)

4499.999999999996

# Linear Regression (sklearn)

In [52]:
regression = LinearRegression()
regression.fit(x1, y)

print(regression.intercept_) # Miejsce przecięcia z osią Y.
print(regression.coef_[0]) # w1

2750.0
250.0
