<a href="https://colab.research.google.com/github/z-zaremska/PK_ML_Bootcamp/blob/master/supervised/02_regression/02_gradient_descent_zz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

# from sklearn import

In [ ]:
x1 = np.array([1, 2, 3, 4, 5, 6])
y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(x1)

In [ ]:
x1 = x1.reshape(m, 1)
y = y.reshape(m, 1)

In [ ]:
bias = np.ones((m, 1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
x = np.append(bias, x1, axis=1)
x

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

## Losowa initializacja parametrów.



In [ ]:
eta = 0.01 # Wskaźnik uczenia
weights = np.random.randn(2, 1)
weights

array([[-0.33643961],
       [ 0.97710356]])

## Metoda gradientu prostego

In [ ]:
# y = a*x + b
intercept = [] # b
coef = [] # a

for i in range(3000):
  gradient = (2/m) * x.T.dot(x.dot(weights) - y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2749.95599102]
 [ 250.01027959]]


In [ ]:
df = pd.DataFrame(data={"intercept": intercept, "coef": coef})
df.head()

intercept        coef
0   72.101892  269.037600
1  124.327222  450.715729
2  162.790577  573.629052
3  191.880731  656.566233
4  214.583481  712.309491

## Wizualizacja dopasowania

In [ ]:
px.line(df, y="intercept", width=800, title="Fit: intercept")

In [ ]:
px.line(df, y="coef", width=800, title="Fit: coef")